name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd
    
    # Decode and create files dynamically
    - name: Create JSON files
      run: |
          mkdir -p Creds
          echo "${{ secrets.CREDENTIALS }}" > Creds/credentials.json
          echo "${{ secrets.SKILFUL_MERCURY_444620 }}" > Creds/skilful-mercury-444620-s6-2526f9ed3422.json
          echo "${{ secrets.TOKEN }}" > Creds/token.json

    - name: "Debug: List Creds directory"
      run: ls -la Creds

    - name: "Debug: Print credentials.json"
      run: cat Creds/credentials.json

    - name: "Debug: Print skilful-mercury-444620-s6-2526f9ed3422.json"
      run: cat Creds/skilful-mercury-444620-s6-2526f9ed3422.json

    - name: "Debug: Print token.json"
      run: cat Creds/token.json

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Create .env file
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        echo "SERVICE_ROLE_KEY=${{ secrets.SERVICE_ROLE_KEY }}" >> .env

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lkgpt-api-v3